# https://devices.esphome.io/devices/Gosund-WP9

substitutions:
  device_name: gosund_wp9_power_strip
  friendly_name: Gosund WP9 Power Strip
  platform: ESP8266
  board: esp01_1m

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password

logger:

captive_portal:

web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: true
      mode: INPUT
    name: "${friendly_name} Power Button"
    id: "${device_name}_power_button"
    on_press:
      then:
        - switch.toggle: "${device_name}_usb"
        # Tied the button to the USB relay
        # - switch.toggle: "${device_name}_switch1"
        # - switch.toggle: "${device_name}_switch2"
        # - switch.toggle: "${device_name}_switch3"
switch:
  - platform: gpio
    name: "${friendly_name} Switch1"
    id: "${device_name}_switch1"
    pin: GPIO14
    restore_mode: "RESTORE_DEFAULT_ON"
    on_turn_on:
      - switch.turn_on: led_2
    on_turn_off:
      - switch.turn_off: led_2
  - platform: gpio
    name: "${friendly_name} Switch2"
    id: "${device_name}_switch2"
    pin: GPIO12
    restore_mode: "RESTORE_DEFAULT_ON"
    on_turn_on:
      - switch.turn_on: led_3
    on_turn_off:
      - switch.turn_off: led_3
  - platform: gpio
    name: "${friendly_name} Switch3"
    id: "${device_name}_switch3"
    pin: GPIO13
    restore_mode: "RESTORE_DEFAULT_ON"
    on_turn_on:
      - switch.turn_on: led_4
    on_turn_off:
      - switch.turn_off: led_4
  - platform: gpio
    name: "${friendly_name} usb"
    id: "${device_name}_usb"
    pin: GPIO05
    restore_mode: "RESTORE_DEFAULT_ON"
    on_turn_on:
      - switch.turn_on: led_1
    on_turn_off:
      - switch.turn_off: led_1
  - platform: gpio
    id: led_1
    pin: GPIO0
    inverted: yes
  - platform: gpio
    id: led_2
    pin: GPIO3
    inverted: no
  - platform: gpio
    id: led_3
    pin: GPIO2
    inverted: no
  - platform: gpio
    id: led_4
    pin: GPIO1
    inverted: no