substitutions:
  name: kauf-bulb-a15-05
  friendly_name: Kauf Bulb a19 05
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
api:
  encryption:
    key: u8e4lVNJ8kfaFgjv9NkujaXY5fGvhI5UxQZ8UZoSZIs=


wifi:
  ssid: !secret wifi_ssid_not_o
  password: !secret wifi_not_password
