substitutions:
  name: kauf-bulb-a15-04
  friendly_name: Kauf Bulb a19 04
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
api:
  encryption:
    key: dY7IkiRC7kDk7gHZDslnoOzV2WuMySQijaOIrtUP4Mo=


wifi:
  ssid: !secret wifi_ssid_not_o
  password: !secret wifi_not_password
