# Light dimmer
# https://devices.esphome.io/devices/MJ-SJ01
substitutions:
  location: Aubrey's Room
  project_name: AnthonyD42.MJ-SD01
  project_version: "1.0"
  device_name: mj_sd01_dimmer_06 # hostname & entity_id
  friendly_name: MJ-SD01 Dimmer 06 # Displayed in HA frontend
  # fan_entity: fan.sonoff_ifan04_04_fan
  # light_entity: light.sonoff_ifan04_04_light
  # led_entity: switch.gosund_wp3_plug_02

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  platformio_options:
    build_flags:
      - -DNDEBUG
      - -Os

esp8266:
  board: esp01_1m
  restore_from_flash: true

api:
  encryption:
    key: !secret api_encryption_key
  # Expose the script as a service to HA
  actions:
    - action: update_leds
      variables:
        my_led_mode: string
      then:
        - script.execute:
            id: update_leds
            mode: !lambda 'return my_led_mode;'

ota:
  - platform: esphome
    password: !secret ota_password

wifi:  
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  version: 3

logger:
  level: WARN
  baud_rate: 0

# GPI Mappings
# GPIO0 - Up button (input, pullup, inverted)
# GPIO1 - Down button (input, pullup, inverted)
# GPIO3 - LED 5 (output, inverted)
# GPIO4 - Status LED Red (output, inverted)
# GPIO5 - LED 4 (output, inverted)
# GPIO12 - LED 3 (output, inverted)
# GPIO13 - PWM output to dimmer (output, esp8266_pwm)
# GPIO14 - LED 2 (output, inverted)
# GPIO15 - Main button (input, pullup)
# GPIO16 - Relay control (output, inverted)

binary_sensor:
  - platform: gpio
    id: main_button
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
    name: "Main Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                button_name: ${device_name}_main_single

      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                button_name: ${device_name}_main_double

  - platform: gpio
    id: up_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Up Button"
    on_press:
      - homeassistant.event:
          event: esphome.button_pressed
          data:
            button_name: ${device_name}_up

  - platform: gpio
    id: down_button
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "Down Button"
    on_press:
      - homeassistant.event:
          event: esphome.button_pressed
          data:
            button_name: ${device_name}_down

button:
  - platform: restart
    name: "ESP8266 Restart"
    icon: mdi:power-cycle
    entity_category: diagnostic

  - platform: factory_reset
    name: "ESP8266 Factory Reset"
    icon: mdi:restart-alert
    entity_category: diagnostic

output:
  - platform: gpio
    pin: GPIO4
    id: red_led
    inverted: true
  - platform: gpio
    pin: GPIO16
    id: led1 # Relay LED
    inverted: true
  - platform: gpio
    pin: GPIO14
    id: led2
    inverted: true
  - platform: gpio
    pin: GPIO12
    id: led3
    inverted: true
  - platform: gpio
    pin: GPIO5
    id: led4
    inverted: true
  - platform: gpio
    pin: GPIO3
    id: led5
    inverted: true

# Script to update LEDs based on HA command
script:
  - id: update_leds
    parameters:
      mode: string
    then:
      - if:
          condition:
            lambda: 'return mode == "light_on";'
          then:
            - output.turn_off: red_led
      - if:
          condition:
            lambda: 'return mode == "light_off";'
          then:
            - output.turn_on: red_led

      - if:
          condition:
            lambda: 'return mode == "fan_off";'
          then:
            - output.turn_off: led1
            - output.turn_off: led2
            - output.turn_off: led3
            - output.turn_off: led4
            - output.turn_off: led5

      - if:
          condition:
            lambda: 'return mode == "fan_low";'
          then:
            - output.turn_on: led1
            - output.turn_off: led2
            - output.turn_off: led3
            - output.turn_off: led4
            - output.turn_off: led5

      - if:
          condition:
            lambda: 'return mode == "fan_medium";'
          then:
            - output.turn_on: led1
            - output.turn_on: led2
            - output.turn_on: led3
            - output.turn_off: led4
            - output.turn_off: led5

      - if:
          condition:
            lambda: 'return mode == "fan_high";'
          then:
            - output.turn_on: led1
            - output.turn_on: led2
            - output.turn_on: led3
            - output.turn_on: led4
            - output.turn_on: led5

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
    icon: mdi:wifi

text_sensor:
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic
    icon: mdi:information-outline
