# https://devices.esphome.io/devices/Shelly-1

# Garage Gas Lights Project
substitutions:
  location: Garage Gas Lights
  project_name: AnthonyD42.Shelly 1
  project_version: "1.0"
  device_name: shelly_1_01
  friendly_name: Shelly 1 01

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  platformio_options:
    build_flags:
      - -DNDEBUG
      - -Os

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
- platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password

# to provision wifi credentials to the device.
captive_portal:

# https://esphome.io/components/web_server.html
web_server:
  port: 80
  version: 3

# https://esphome.io/components/logger
logger:
  level: WARN
  baud_rate: 0

mdns:
  disabled: false

binary_sensor:
- platform: gpio
  pin:
    number: GPIO5
  name: "Switch"
  on_state:
    # the rotary switch changes from off to on, we do not care about that, only that it changes state and toggles the lights.
    then:
    - light.toggle: light_1

button:
  - platform: restart
    name: "ESP8266 Restart"
    icon: mdi:power-cycle
    entity_category: diagnostic

  - platform: factory_reset
    name: "ESP8266 Factory Reset"
    icon: mdi:restart-alert
    entity_category: diagnostic

light:
- platform: binary
  name: "Light"
  output: relay_1
  id: light_1

output:
- platform: gpio
  pin: GPIO4
  id: relay_1

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
- platform: version
  name: "ESPHome Version"
