# https://devices.esphome.io/devices/Shelly-1

substitutions:
  device_name: shelly_1_03
  friendly_name: Shelly 1 03

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# To be able to get logs from the device via serial and api.
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

web_server:

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO4
    id: relay_1

light:
  - platform: binary
    name: "Light"
    output: relay_1
    id: light_1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      #mode: INPUT_PULLUP
      #inverted: True
    name: "Button"
    on_press:
      then:
        - light.toggle: light_1

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "ESPHome Version"