# https://devices.esphome.io/devices/Shelly-1

#Landing Lights Lvl 2
substitutions:
  location: 2nd Floor Landing Lights
  project_name: AnthonyD42.Shelly 1
  project_version: "1.0"
  device_name: shelly_1_02
  friendly_name: Shelly 1 02
  remote_device_01: switch.mj_s01_switch_12_switch # Long Press - Girls Bathroom Lights
  remote_device_02: light.mj_sd01_dimmer_01_light # Double Click - Steampunk Lamp

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  platformio_options:
    build_flags:
      - -DNDEBUG
      - -Os

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password
    # Sets up the improv via serial client for Wi-Fi provisioning

captive_portal:

# https://esphome.io/components/web_server.html
web_server:
  port: 80
  version: 3

# https://esphome.io/components/logger
logger:
  level: WARN
  baud_rate: 0

mdns:
  disabled: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: light_1
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - homeassistant.event:
              event: esphome.button_long_pressed
              data:
                button_name: "Main Button"
          # - homeassistant.service:
          #     service: homeassistant.turn_off
          #     data:
          #       entity_id: ${remote_device_01}
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - homeassistant.event:
              event: esphome.button_double_pressed
              data:
                button_name: "Main Button"
          # - homeassistant.service:
          #     service: homeassistant.turn_off
          #     data:
          #       entity_id: ${remote_device_02}

button:
  - platform: restart
    name: "ESP8266 Restart"
    icon: mdi:power-cycle
    entity_category: diagnostic

  - platform: factory_reset
    name: "ESP8266 Factory Reset"
    icon: mdi:restart-alert
    entity_category: diagnostic

light:
  - platform: binary
    name: "Light"
    output: relay_1
    id: light_1
    # on_turn_on: #blue when on
    #   - homeassistant.service:
    #       service: homeassistant.turn_on
    #       data:
    #         entity_id: switch.mj_s01_switch_03_blue_led
    #   - homeassistant.service:
    #       service: homeassistant.turn_off
    #       data:
    #         entity_id: switch.mj_s01_switch_03_red_led
    # on_turn_off: #red when off
    #   - homeassistant.service:
    #       service: homeassistant.turn_off
    #       data:
    #         entity_id: switch.mj_s01_switch_03_blue_led
    #   - homeassistant.service:
    #       service: homeassistant.turn_on
    #       data:
    #         entity_id: switch.mj_s01_switch_03_red_led

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO4
    id: relay_1

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic