# https://devices.esphome.io/devices/TanTan-WP3

substitutions:
  device_name: tantan_wp3_plug_02
  friendly_name: TanTan WP3 Plug 02

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - switch.turn_on: red_led
      - delay: 5s
      - switch.turn_off: red_led

esp8266:
  board: esp8285

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password

# Enable logging
logger:

# Enable fallback hotspot (http://192.168.4.1/)
captive_portal:

web_server:

binary_sensor:
  # Connected to HA
  - platform: status
    name: "Status"

  # the on off button
  - platform: gpio
    pin: GPIO04
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms
      - delayed_on_off: 100ms
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${device_name}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${device_name}_uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
    id: "${device_name}_esphome_version"

switch:
  # the relay that controls the output power
  - platform: gpio
    pin: GPIO14
    name: "${friendly_name}"
    id: relay
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  # the indicator leds in the on off button
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
    id: red_led

  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    id: blue_led