# https://community.home-assistant.io/t/teckin-ss31-outdoor-wifi-plug/245691/3

substitutions:
  device_name: teckin_ss31_01
  friendly_name: Teckin SS31 01

esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  friendly_name: "${friendly_name}"

esp8266:
  board: esp8285

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  version: 3

logger:

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${device_name}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${device_name}_uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"
    id: "${device_name}_esphome_version"

status_led:
  pin: 
    number: GPIO4
    inverted: True

output:
  - platform: gpio
    id: relay_status
    pin: GPIO5
    inverted: True

switch:
  - platform: gpio
    name: "${friendly_name} Relay 1"
    pin: GPIO12
    id: relay_1
    on_turn_on:
          then:
            - if:
                condition:
                  and:
                    - switch.is_off: relay_2
                then:
                  - output.turn_on: relay_status
    on_turn_off:
          then:
            - if:
                condition:
                  and:
                    - switch.is_off: relay_2
                then:
                  - output.turn_off: relay_status
  - platform: gpio
    name: "${friendly_name} Relay 2"
    pin: GPIO14
    id: relay_2
    on_turn_on:
          then:
            - if:
                condition:
                  and:
                    - switch.is_off: relay_1
                then:
                  - output.turn_on: relay_status
    on_turn_off:
          then:
            - if:
                condition:
                  and:
                    - switch.is_off: relay_1
                then:
                  - output.turn_off: relay_status

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_1
      - switch.toggle: relay_2
    name: "${friendly_name} Button"