# https://aaronredding.com/esphome-treatlife-smart-dimmer-plug-with-2-sockets-dp12/
substitutions:
  location: Outside
  project_name: AnthonyD42.TreatLife DS10 Dimmer
  project_version: "1.0"
  name: treatlife-ds10-dimmer-plug-01
  friendly_name: TreatLife DS10 Dimmer Plug 01
  device_description: "Treatlife DP10 Smart Dimmer Plug with 1 Socket"
  icon: mdi:power-socket-us

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  platformio_options:
    build_flags:
      - -DNDEBUG
      - -Os
  on_boot:
    priority: 600
    then:
      lambda: |-
        // seed the C PRNG and set initial brightness
        srand((unsigned int) ::millis());
        id(Outlet1).remote_values.set_brightness(100);
        // id(Outlet2).remote_values.set_brightness(100);

bk72xx:
  board: cb3s

logger:
  level: INFO  # Reduced from DEBUG to minimize spooky mode spam
  baud_rate: 0
  logs:
    light: WARN  # Only log actual errors for light component
    api: WARN    # Only log connection issues

web_server:
  port: 80
  version: 3

captive_portal:

mdns:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: !secret ap_password

time:
  - platform: homeassistant
    id: homeassistant_time

globals:
  - id: spooky_mode
    type: bool
    initial_value: 'false'
  - id: spooky_min_pct
    type: int
    initial_value: '10'
  - id: spooky_max_pct
    type: int
    initial_value: '80'
  - id: spooky_interval_ms
    type: int
    initial_value: '1000'
  - id: last_spooky_pct
    type: int
    initial_value: '-1'
  - id: next_spooky_pct
    type: int
    initial_value: '0'

button:
  - platform: restart
    name: "Restart"
    icon: mdi:power-cycle
    entity_category: diagnostic

text_sensor:
  - platform: version
    name: ESPHome Version
    entity_category: diagnostic
    icon: "mdi:information-outline"
  - platform: libretiny
    version:
      name: LibreTiny Version

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

# Disabled debug updates to reduce memory usage during spooky mode
# debug:
#   update_interval: 30s

# DPIDs processed from schema model: 000004cn7x
tuya:
  time_id: homeassistant_time # This links the Tuya component to the time component

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 300s
    entity_category: diagnostic
    icon: "mdi:wifi"
    
light:
  - platform: "tuya"
    name: Outlet 1
    id: Outlet1
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 100
    max_value: 1000

#   - platform: "tuya"
#     name: ${device_friendly_name} Outlet 2
#     id: Outlet2
#     dimmer_datapoint: 8
#     switch_datapoint: 7
#     min_value: 100
#     max_value: 1000

select:
  - platform: "tuya"
    id: "dimmer_mode"
    name: Dimming Mode
    enum_datapoint: 4
    options:
      0: LED # Index 0
      1: Incandescent # Index 1
      2: Halogen # Index 2

  # Local UI select to pick normal vs spooky effect (appears in web UI)
  - platform: template
    name: "Effect Mode"
    id: effect_mode
    optimistic: true
    options:
      - "Normal"
      - "Spooky"
    set_action:
      - lambda: |-
          // When the user selects Spooky, enable the spooky routine
          if (x == "Spooky") {
            id(spooky_mode) = true;
          } else {
            id(spooky_mode) = false;
          }

number:
  - platform: "tuya"
    name: "Minimum Brightness"
    id: min_brightness
    number_datapoint: 3
    min_value: 10
    max_value: 1000
    step: 1

  # UI numbers to configure spooky effect range (percent)
  - platform: template
    name: "Spooky Minimum Brightness (%)"
    id: spooky_min_number
    min_value: 1
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          id(spooky_min_pct) = (int) x;
    lambda: |-
      return (float) id(spooky_min_pct);

  - platform: template
    name: "Spooky Maximum Brightness (%)"
    id: spooky_max_number
    min_value: 1
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          id(spooky_max_pct) = (int) x;
    lambda: |-
      return (float) id(spooky_max_pct);

  - platform: template
    name: "Spooky Interval (s)"
    id: spooky_interval_number
    min_value: 0.25
    max_value: 2.0
    step: 0.1
    set_action:
      - lambda: |-
          // store milliseconds in global
          int ms = (int) (x * 1000.0);
          if (ms < 250) ms = 250; // enforce a safer minimum 250ms to avoid overwhelming web server/EventSource
          id(spooky_interval_ms) = ms;
    lambda: |-
      return (float) id(spooky_interval_ms) / 1000.0;

interval:
  # Base interval runs frequently; an internal timer uses the runtime-configurable
  # `spooky_interval_ms` to decide when to actually change brightness. This lets
  # us change the interval from the UI without recompiling.
  - interval: 200ms
    then:
      - if:
          condition:
            lambda: |-
              // Only fire when spooky mode is enabled and the configured
              // interval has elapsed. Use millis() to track elapsed time.
              // Compute a candidate brightness and only return true if it's
              // different from the last sent value. This reduces duplicate
              // sends and helps avoid stuck EventSource warnings.
              static unsigned long last = 0;
              unsigned long now = ::millis();
              if (!id(spooky_mode)) return false;
              unsigned long wait = (unsigned long) id(spooky_interval_ms);
              if (wait < 250) wait = 250;
              if (now - last < wait) return false;

              int minp = id(spooky_min_pct);
              int maxp = id(spooky_max_pct);
              if (minp < 1) minp = 1;
              if (maxp > 100) maxp = 100;
              if (minp > maxp) { int t = minp; minp = maxp; maxp = t; }
              int r = minp + (rand() % (maxp - minp + 1));
              id(next_spooky_pct) = r;
              if ((int) id(last_spooky_pct) == r) {
                // keep waiting for a different value
                return false;
              }
              last = now;
              return true;
          then:
            - light.turn_on:
                id: Outlet1
                brightness: !lambda |-
                  return (float) id(next_spooky_pct) / 100.0;
            - lambda: |-
                // record last sent value to avoid repeats
                id(last_spooky_pct) = id(next_spooky_pct);


# You need to adjust it manually: in most cases, use either 9600 or 115200
# W: UPK: Missing mapping for DP 1, BOOL(rw), switch_led_1 (开关1)
# W: UPK: Missing mapping for DP 2, VALUE(rw), bright_value_1 (亮度值)
# W: UPK: Missing mapping for DP 3, VALUE(rw), brightness_min_1 (最小亮度1)
# W: UPK: Missing mapping for DP 4, ENUM(rw), led_type_1 (光源类型1)
# W: UPK: Converter 'base' couldn't process DP 101, RAW(rw), wake_up (wake-up)
# W: UPK: Missing mapping for DP 102, VALUE(rw), count_down (count_down)
# W: UPK: Missing mapping for DP 103, VALUE(rw), bright_value_3 (亮度值（关灯时下发）)
# W: UPK: Missing mapping for DP 104, VALUE(rw), indicator (指示灯控制)
# W: UPK: Converter 'base' couldn't process DP 105, RAW(rw), random_time (离家模式)


# # # The below items are settings imported from LibreTiny
# switch:
#   - platform: tuya
#     switch_datapoint: 1
#     name: (Unconfirmed) Switch Led 1

# number:
#   - platform: tuya
#     number_datapoint: 2
#     name: (Unconfirmed) Bright Value 1
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 3
#     name: (Unconfirmed) Brightness Min 1
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 102
#     name: (Unconfirmed) Count Down
#     min_value: 0
#     max_value: 1440
#     step: 1
#   - platform: tuya
#     number_datapoint: 103
#     name: (Unconfirmed) Bright Value 3
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 104
#     name: (Unconfirmed) Indicator
#     min_value: 0
#     max_value: 2
#     step: 1

# select:
#   - platform: tuya
#     enum_datapoint: 4
#     name: (Unconfirmed) Led Type 1
#     optimistic: true
#     options:
#       0: Led
#       1: Incandescent
#       2: Halogen
