substitutions:
  name: treatlife-ds03-02
  friendly_name: TreatLife DS03 02

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:
  port: 80
  version: 3

captive_portal:

mdns:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: !secret ap_password

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s
  - platform: uptime
    name: Uptime

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

# DPIDs processed from schema model: 000003ibqy
tuya:
  time_id: homeassistant_time # This links the Tuya component to the time component
    
light:
  - platform: "tuya"
    name: Light
    dimmer_datapoint: 6
    switch_datapoint: 101
    min_value: 100
    max_value: 1000

fan:
  - platform: "tuya"
    name: Speed
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4

# # The below items are settings imported from LibreTiny
# select:
#   - platform: tuya
#     switch_datapoint: 1
#     name: Switch Fan
#   - platform: tuya
#     switch_datapoint: 101
#     name: Light

# select:
#   - platform: tuya
#     enum_datapoint: 3
#     name: Fan Speed Enum
#     optimistic: true
#     options:
#       0: "1"
#       1: "2"
#       2: "3"
#       3: "4"
#   - platform: tuya
#     enum_datapoint: 106
#     name: Light Mode1
#     optimistic: true
#     options:
#       0: Mode1
#       1: Mode2
#       2: Mode3

# number:
#   - platform: tuya
#     number_datapoint: 6
#     name: Bright Value
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 102
#     name: Fan Countdown
#     unit_of_measurement: ""
#     min_value: 0
#     max_value: 1440
#     step: 1
#   - platform: tuya
#     number_datapoint: 103
#     name: Light Count Down
#     unit_of_measurement: ""
#     min_value: 0
#     max_value: 1440
#     step: 1
#   - platform: tuya
#     number_datapoint: 105
#     name: Lowest Brightness
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 108
#     name: Indicator
#     min_value: 0
#     max_value: 2
#     step: 1
