# https://aaronredding.com/esphome-treatlife-smart-dimmer-plug-with-2-sockets-dp12/
substitutions:
  name: treatlife-ds10-dimmer-plug-01
  friendly_name: TreatLife DS10 Dimmer Plug 01
  device_description: "Treatlife DP10 Smart Dimmer Plug with 1 Socket"
  icon: mdi:power-socket-us
  update_interval_wifi: "60s"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600
    then:
      lambda: |-
        id(Outlet1).remote_values.set_brightness(100);
        // id(Outlet2).remote_values.set_brightness(100);

bk72xx:
  board: cb3s

logger:
  level: DEBUG
  baud_rate: 0

web_server:
  port: 80
  version: 3

captive_portal:

mdns:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  use_address: 192.168.30.242
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: !secret ap_password

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: version
    name: Version
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

debug:
  update_interval: 30s

# DPIDs processed from schema model: 000004cn7x
tuya:
  time_id: homeassistant_time # This links the Tuya component to the time component

sensor:
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s
  - platform: uptime
    name: Uptime
    unit_of_measurement: minutes
    filters:
      - lambda: return x / 60.0;
    
light:
  - platform: "tuya"
    name: Outlet 1
    id: Outlet1
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 100
    max_value: 1000
#   - platform: "tuya"
#     name: ${device_friendly_name} Outlet 2
#     id: Outlet2
#     dimmer_datapoint: 8
#     switch_datapoint: 7
#     min_value: 100
#     max_value: 1000

select:
  - platform: "tuya"
    id: "dimmer_mode"
    name: Dimming Mode
    enum_datapoint: 10
    options:
      0: LED # Index 0
      1: Incandescent # Index 1
      2: Halogen # Index 2
#1 - switch 1
#2 - dimmer 1 = 763
#3 - dimmer 1 - brightness min = 100 Diming Range 10%= 100, 100%=1000
#7 - switch 2
#8 - dimmer 2 = 763
#9 - dimmer 2 - brightness min = 100 Diming Range 10%= 100, 100%=1000
#10 - dimming mode = LED, incandescent, halogen

# # # The below items are settings imported from LibreTiny
# switch:
#   - platform: tuya
#     switch_datapoint: 1
#     name: (Unconfirmed) Switch Led 1

# number:
#   - platform: tuya
#     number_datapoint: 2
#     name: (Unconfirmed) Bright Value 1
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 3
#     name: (Unconfirmed) Brightness Min 1
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 102
#     name: (Unconfirmed) Count Down
#     min_value: 0
#     max_value: 1440
#     step: 1
#   - platform: tuya
#     number_datapoint: 103
#     name: (Unconfirmed) Bright Value 3
#     min_value: 10
#     max_value: 1000
#     step: 1
#   - platform: tuya
#     number_datapoint: 104
#     name: (Unconfirmed) Indicator
#     min_value: 0
#     max_value: 2
#     step: 1

# select:
#   - platform: tuya
#     enum_datapoint: 4
#     name: (Unconfirmed) Led Type 1
#     optimistic: true
#     options:
#       0: Led
#       1: Incandescent
#       2: Halogen
