substitutions:
  location: "Garage Controler for Lights"
  project_name: AnthonyD42.Zemismart-KS-811
  project_version: "1.0"
  device_name: zemismart_ks_811
  friendly_name: "Zemismart KS-811"

  switch_restore_mode: RESTORE_DEFAULT_OFF
  switch1_name: "Middle Lights"
  switch2_name: "Side Lights"
  switch3_name: "Gas Lights"
  remote_entity1_name: "light.shelly_25_02_light_1" # Middle Lights
  remote_entity2_name: "light.shelly_25_02_light_2" # Side Lights
  remote_entity3_name: "light.shelly_1_01_light" # Gas Lights

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  platformio_options:
    build_flags:
      - -DNDEBUG
      - -Os
  on_boot:
    - priority: 600.0
      then:
        - delay: 10s
        - if:
            condition:
              binary_sensor.is_on: remote_entity1
            then:
              - switch.turn_on: relay1
            else:
              - switch.turn_off: relay1
        - if:
            condition:
              binary_sensor.is_on: remote_entity2
            then:
              - switch.turn_on: relay2
            else:
              - switch.turn_off: relay2
        - if:
            condition:
              binary_sensor.is_on: remote_entity3
            then:
              - switch.turn_on: relay3
            else:
              - switch.turn_off: relay3

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password
    # Sets up the improv via serial client for Wi-Fi provisioning

captive_portal:

# https://esphome.io/components/web_server.html
web_server:
  port: 80
  version: 3

# https://esphome.io/components/logger
logger:
  level: WARN
  baud_rate: 0

mdns:
  disabled: false

binary_sensor:
  - platform: homeassistant
    entity_id: ${remote_entity1_name} # "Middle Lights"
    id: remote_entity1
  
  - platform: homeassistant
    entity_id: ${remote_entity2_name} # Side Lights
    id: remote_entity2
  
  - platform: homeassistant
    entity_id: ${remote_entity3_name} # Gas Lights
    id: remote_entity3

  - platform: gpio
    id: button1
    pin:
      number: GPIO16
      mode: INPUT
      inverted: true
    on_click:
      then:
        - logger.log: "Button 1 pressed - Toggling ${switch1_name}"
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button_name: ${device_name}_button1_pressed

  - platform: gpio
    id: button2
    pin:
      number: GPIO5
      inverted: true
      mode: INPUT_PULLUP
    on_click:
      then:
        - logger.log: "Button 2 pressed - Toggling ${switch2_name}"
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button_name: ${device_name}_button2_pressed

  - platform: gpio
    id: button3
    pin:
      number: GPIO4
      inverted: true
      mode: INPUT_PULLUP
    on_click:
      then:
        - logger.log: "Button 3 pressed - Toggling ${switch2_name}"
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button_name: ${device_name}_button3_pressed

button:
  - platform: restart
    name: "ESP8266 Restart"
    icon: mdi:power-cycle
    entity_category: diagnostic

  - platform: factory_reset
    name: "ESP8266 Factory Reset"
    icon: mdi:restart-alert
    entity_category: diagnostic

light:
  - platform: status_led
    id: led_green
    name: Backlight
    restore_mode: ALWAYS_ON
    entity_category: config
    pin:
      number: GPIO0
      inverted: true

# output:

# script:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
      
switch:
  - platform: gpio
    name: ${switch1_name}  # Middle Lights
    pin: GPIO13
    id: relay1
    restore_mode: ${switch_restore_mode}

  - platform: gpio
    name: ${switch2_name} # Side Lights
    pin: GPIO12
    id: relay2
    restore_mode: ${switch_restore_mode}

  - platform: gpio
    name: ${switch3_name} # Gas Lights
    pin: GPIO14
    id: relay3
    restore_mode: ${switch_restore_mode}

text_sensor:
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic