substitutions:
  name: kauf-bulb-02db9f
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: cZJHKo1CALwENUy/uJ8nh2cwpKCthlXlBp09G7L2oK8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
