substitutions:
  name: kauf-bulb-a15-01
  friendly_name: Kauf Bulb a15 01
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
api:
  encryption:
    key: "xQJun9MFZV3YNtMP/mkk24rACOhkKkBsFLlF3TgfENA="


wifi:
  ssid: !secret wifi_ssid_not_o
  password: !secret wifi_not_password
