substitutions:
  name: treatlife-ds03-02
  friendly_name: TreatLife DS03 02

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "3qPPWkLgBJnvherGyZGehUe3jGh+OoGPJbh+pFJ7wCc="

ota:
  - platform: esphome
    password: "5c72712898f0b438058dd4be747d92ef"

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_not_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} Fallback AP
    password: !secret wifi_not_password


web_server:
  
captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:

sensor:
  - platform: wifi_signal
    name: $friendly_name Wifi Signal
    update_interval: 60s

  - platform: uptime
    name: $friendly_name uptime

light:
  - platform: "tuya"
    name: $friendly_name Light
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value: 100
    max_value: 1000

fan:
  - platform: "tuya"
    name: $friendly_name Speed
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
    