substitutions:
  location: ""
  project_name: AnthonyD42.[device_name]
  project_version: "1.0"
  device_name: ""
  friendly_name: ""
  # remote_device_01: ""
  # remote_device_02: ""

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${project_version}
  platformio_options:
    build_flags:
      - -DNDEBUG
      - -Os

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable over the air update with password
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password
    # Sets up the improv via serial client for Wi-Fi provisioning

captive_portal:

# https://esphome.io/components/web_server.html
web_server:
  port: 80
  version: 3

# https://esphome.io/components/logger
logger:
  level: WARN
  baud_rate: 0

mdns:
  disabled: false

# globals:

# number:

# binary_sensor:

button:
  - platform: restart
    name: "ESP8266 Restart"
    icon: mdi:power-cycle
    entity_category: diagnostic

  - platform: factory_reset
    name: "ESP8266 Factory Reset"
    icon: mdi:restart-alert
    entity_category: diagnostic

# light:

# output:

# script:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
    icon: "mdi:wifi"

# switch:

text_sensor:
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic
    icon: "mdi:information-outline"